In [3]:
import pandas as pd

In [4]:
import seaborn as sns

In [5]:
df = pd.read_csv("TWO_CENTURIES_OF_UM_RACES.csv")

C:\Users\jacob\AppData\Local\Temp\ipykernel_6772\2350612576.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("TWO_CENTURIES_OF_UM_RACES.csv")

In [6]:
#See the data that's been imported

In [7]:
df.head(10)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,06.01.2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,06.01.2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
3,2018,06.01.2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3
4,2018,06.01.2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4
5,2018,06.01.2018,Selva Costera (CHI),50km,22,6:25:01 h,NaN,ARG,1974.0,M,M40,7.792,5
6,2018,06.01.2018,Selva Costera (CHI),50km,22,6:28:00 h,Los Patagones,ARG,1979.0,F,W35,7.732,6
7,2018,06.01.2018,Selva Costera (CHI),50km,22,6:32:24 h,Reaktiva Chile,CHI,1967.0,F,W50,7.645,7
8,2018,06.01.2018,Selva Costera (CHI),50km,22,6:39:08 h,Puro Trail Osorno,CHI,1985.0,M,M23,7.516,8
9,2018,06.01.2018,Selva Costera (CHI),50km,22,6:45:11 h,Marlene Flores Team,CHI,1976.0,M,M40,7.404,9

In [8]:
df.shape

(7461195, 13)

In [9]:
df.dtypes

Year of event                  int64
Event dates                   object
Event name                    object
Event distance/length         object
Event number of finishers      int64
Athlete performance           object
Athlete club                  object
Athlete country               object
Athlete year of birth        float64
Athlete gender                object
Athlete age category          object
Athlete average speed         object
Athlete ID                     int64
dtype: object

In [10]:
#clean up data

In [11]:
#Only want USA Races, 50k or 50Mi, 2020

In [12]:
#step 1 show 50km or 50mi
#50km
#50mi

In [18]:
runs_2000 = df[(df['Athlete gender'] == 'M') & (df['Event distance/length'] == '50mi') & (df['Year of event'] >= 2000)]

In [16]:
df[(df['Athlete gender'] == 'F') & (df['Event distance/length'] == '50mi')]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
56,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,11:09:35 h,"*Waterloo, ON",CAN,1977.0,F,W40,7.211,56
62,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,12:39:36 h,"*Grand Rapids, MI",USA,1977.0,F,W40,6.356,62
63,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,13:24:05 h,"*Lansing, MI",USA,1990.0,F,W23,6.004,63
1074,2018,24.03.2018,OPSF Ultra 50 Mile (USA),50mi,4,14:54:06 h,"*Centerville, OH",USA,1972.0,F,W45,5.4,1072
1129,2018,24.03.2018,TDR Trail Trashed 50M (USA),50mi,21,11:34:13 h,"*Las Vegas, NV",USA,1980.0,F,W35,6.955,1127
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7461175,1995,07.01.1995,Avalon Benefit 50-Mile Run (USA),50mi,92,11:50:45 h,NaN,USA,1950.0,F,W40,6793.0,1073038
7461178,1995,07.01.1995,Avalon Benefit 50-Mile Run (USA),50mi,92,11:58:02 h,NaN,USA,1961.0,F,W23,6724.0,1308247
7461183,1995,07.01.1995,Avalon Benefit 50-Mile Run (USA),50mi,92,12:03:26 h,NaN,USA,1934.0,F,W60,6674.0,416139
7461184,1995,07.01.1995,Avalon Benefit 50-Mile Run (USA),50mi,92,12:03:26 h,NaN,USA,1951.0,F,W40,6674.0,1098098
7461185,1995,07.01.1995,Avalon Benefit 50-Mile Run (USA),50mi,92,12:05:59 h,NaN,USA,1947.0,F,W45,6650.0,1626367

In [20]:
runs_2000.plot(kind="hist", title="plot")